// Generated by CoffeeScript 1.7.1
(function() {
  require(['$api/models', '$api/audio', 'scripts/asciivis', 'scripts/playlist-example'], function(models, audio, asciivis, playlistExample) {
    'use strict';
    asciivis.doAsciiVis();
    return playlistExample.doPlaylistForAlbum();
  });

}).call(this);
